<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-TeamBuilderPokemon-1d085244-1e1e-4877-938d-932b357167ff</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="8.0.30" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.30" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.30" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.30" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.30" />
  </ItemGroup>

</Project>
