// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeamBuilderPokemon.Data;

#nullable disable

namespace TeamBuilderPokemon.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260923062013_CatalogoTimesEHistorico")]
    partial class CatalogoTimesEHistorico
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.30");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TeamBuilderPokemon.Models.Pokemon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DexNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type2")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Pokemons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DexNumber = 1,
                            Name = "Bulbasaur",
                            Type1 = "Grass",
                            Type2 = "Poison"
                        },
                        new
                        {
                            Id = 2,
                            DexNumber = 4,
                            Name = "Charmander",
                            Type1 = "Fire"
                        },
                        new
                        {
                            Id = 3,
                            DexNumber = 7,
                            Name = "Squirtle",
                            Type1 = "Water"
                        },
                        new
                        {
                            Id = 4,
                            DexNumber = 25,
                            Name = "Pikachu",
                            Type1 = "Electric"
                        },
                        new
                        {
                            Id = 5,
                            DexNumber = 133,
                            Name = "Eevee",
                            Type1 = "Normal"
                        },
                        new
                        {
                            Id = 6,
                            DexNumber = 66,
                            Name = "Machop",
                            Type1 = "Fighting"
                        },
                        new
                        {
                            Id = 7,
                            DexNumber = 92,
                            Name = "Gastly",
                            Type1 = "Ghost",
                            Type2 = "Poison"
                        },
                        new
                        {
                            Id = 8,
                            DexNumber = 95,
                            Name = "Onix",
                            Type1 = "Rock",
                            Type2 = "Ground"
                        },
                        new
                        {
                            Id = 9,
                            DexNumber = 130,
                            Name = "Gyarados",
                            Type1 = "Water",
                            Type2 = "Flying"
                        },
                        new
                        {
                            Id = 10,
                            DexNumber = 65,
                            Name = "Alakazam",
                            Type1 = "Psychic"
                        },
                        new
                        {
                            Id = 11,
                            DexNumber = 123,
                            Name = "Scyther",
                            Type1 = "Bug",
                            Type2 = "Flying"
                        },
                        new
                        {
                            Id = 12,
                            DexNumber = 149,
                            Name = "Dragonite",
                            Type1 = "Dragon",
                            Type2 = "Flying"
                        },
                        new
                        {
                            Id = 13,
                            DexNumber = 197,
                            Name = "Umbreon",
                            Type1 = "Dark"
                        },
                        new
                        {
                            Id = 14,
                            DexNumber = 208,
                            Name = "Steelix",
                            Type1 = "Steel",
                            Type2 = "Ground"
                        },
                        new
                        {
                            Id = 15,
                            DexNumber = 175,
                            Name = "Togepi",
                            Type1 = "Fairy"
                        },
                        new
                        {
                            Id = 16,
                            DexNumber = 143,
                            Name = "Snorlax",
                            Type1 = "Normal"
                        },
                        new
                        {
                            Id = 17,
                            DexNumber = 144,
                            Name = "Articuno",
                            Type1 = "Ice",
                            Type2 = "Flying"
                        },
                        new
                        {
                            Id = 18,
                            DexNumber = 37,
                            Name = "Vulpix",
                            Type1 = "Fire"
                        },
                        new
                        {
                            Id = 19,
                            DexNumber = 60,
                            Name = "Poliwag",
                            Type1 = "Water"
                        },
                        new
                        {
                            Id = 20,
                            DexNumber = 81,
                            Name = "Magnemite",
                            Type1 = "Electric",
                            Type2 = "Steel"
                        },
                        new
                        {
                            Id = 21,
                            DexNumber = 43,
                            Name = "Oddish",
                            Type1 = "Grass",
                            Type2 = "Poison"
                        },
                        new
                        {
                            Id = 22,
                            DexNumber = 104,
                            Name = "Cubone",
                            Type1 = "Ground"
                        },
                        new
                        {
                            Id = 23,
                            DexNumber = 41,
                            Name = "Zubat",
                            Type1 = "Poison",
                            Type2 = "Flying"
                        },
                        new
                        {
                            Id = 24,
                            DexNumber = 96,
                            Name = "Drowzee",
                            Type1 = "Psychic"
                        },
                        new
                        {
                            Id = 25,
                            DexNumber = 58,
                            Name = "Growlithe",
                            Type1 = "Fire"
                        },
                        new
                        {
                            Id = 26,
                            DexNumber = 74,
                            Name = "Geodude",
                            Type1 = "Rock",
                            Type2 = "Ground"
                        },
                        new
                        {
                            Id = 27,
                            DexNumber = 98,
                            Name = "Krabby",
                            Type1 = "Water"
                        },
                        new
                        {
                            Id = 28,
                            DexNumber = 63,
                            Name = "Abra",
                            Type1 = "Psychic"
                        },
                        new
                        {
                            Id = 29,
                            DexNumber = 27,
                            Name = "Sandshrew",
                            Type1 = "Ground"
                        },
                        new
                        {
                            Id = 30,
                            DexNumber = 39,
                            Name = "Jigglypuff",
                            Type1 = "Normal",
                            Type2 = "Fairy"
                        },
                        new
                        {
                            Id = 31,
                            DexNumber = 179,
                            Name = "Mareep",
                            Type1 = "Electric"
                        },
                        new
                        {
                            Id = 32,
                            DexNumber = 246,
                            Name = "Larvitar",
                            Type1 = "Rock",
                            Type2 = "Ground"
                        },
                        new
                        {
                            Id = 33,
                            DexNumber = 359,
                            Name = "Absol",
                            Type1 = "Dark"
                        },
                        new
                        {
                            Id = 34,
                            DexNumber = 447,
                            Name = "Riolu",
                            Type1 = "Fighting"
                        },
                        new
                        {
                            Id = 35,
                            DexNumber = 361,
                            Name = "Snorunt",
                            Type1 = "Ice"
                        },
                        new
                        {
                            Id = 36,
                            DexNumber = 443,
                            Name = "Gible",
                            Type1 = "Dragon",
                            Type2 = "Ground"
                        });
                });

            modelBuilder.Entity("TeamBuilderPokemon.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("TeamBuilderPokemon.Models.TeamRevision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("TeamRevisions");
                });

            modelBuilder.Entity("TeamBuilderPokemon.Models.TeamSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nickname")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("PokemonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlotNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PokemonId");

                    b.HasIndex("TeamId", "SlotNumber")
                        .IsUnique();

                    b.ToTable("TeamSlots");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TeamBuilderPokemon.Models.TeamRevision", b =>
                {
                    b.HasOne("TeamBuilderPokemon.Models.Team", "Team")
                        .WithMany("Revisions")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("TeamBuilderPokemon.Models.TeamSlot", b =>
                {
                    b.HasOne("TeamBuilderPokemon.Models.Pokemon", "Pokemon")
                        .WithMany()
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TeamBuilderPokemon.Models.Team", "Team")
                        .WithMany("Slots")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pokemon");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("TeamBuilderPokemon.Models.Team", b =>
                {
                    b.Navigation("Revisions");

                    b.Navigation("Slots");
                });
#pragma warning restore 612, 618
        }
    }
}
